### ISSUE TITLE
Examine new headway dataset

### ISSUE THREAD

**Issue by eugenevinitsky** [cathywu/learning-traffic#22]
Get 2:30-3:05 dataset from qijian, do full analysis on the headways.

**Comment by eugenevinitsky** [comment]
Waiting on Qijian to send it to me (he's sick)

**Comment by eugenevinitsky** [comment]
There's some inconsistency between the scipy fits and the matlab fits for the lognorm distribution. Need to resolve this. 
Matlab:
![lognormfit_matlab](https://cloud.githubusercontent.com/assets/7660397/22131331/822fbb0a-de67-11e6-9ec6-b451a34472b4.jpg)
Scipy: 
![figure_1](https://cloud.githubusercontent.com/assets/7660397/22131387/ef862932-de67-11e6-8eef-d6daaffbcac0.png)
Like, what is this nonsense right here.

**Comment by cathywu** [comment]
I just really like your comments.

**Comment by eugenevinitsky** [comment]
You should see my code before it's uploaded haha. Full of brimstone and fury

**Comment by eugenevinitsky** [comment]
Scipy fit is garbage and it chooses not to say so.

**Comment by eugenevinitsky** [comment]
Relevant figures are computed, as was done for other data-sets
