### ISSUE TITLE
Extract velocities using moving exponential filter

### ISSUE THREAD

**Issue by eugenevinitsky** [cathywu/learning-traffic#24]

**Comment by eugenevinitsky** [comment]
Need to compare results to paper, but otherwise is implemented.

**Comment by eugenevinitsky** [comment]
Their plot: 
<img width="293" alt="750_kesting" src="https://cloud.githubusercontent.com/assets/7660397/22353945/c24db884-e3d7-11e6-8530-fb1ab238f639.png">

My plot: 
![750_velocity_unfiltered](https://cloud.githubusercontent.com/assets/7660397/22354176/0d141150-e3d9-11e6-857c-be00eb6a4c0b.png)

The scale isn't the same!

**Comment by eugenevinitsky** [comment]
@cathywu looking at this data...do you think it's worth bothering with the velocities? I'm going to go talk to qijian about this...maybe he knows why this shows up in the NGSIM dataset

**Comment by cathywu** [comment]
Hm, this is the overall plot or the lane change plot?

**Comment by cathywu** [comment]
Are you still looking at only the inner few lanes? Do the spikes correspond
to speed limits, blockages, merge locations? The plot looks oddly
systematic. Would be great to get Qijian's insights on this.

**Comment by eugenevinitsky** [comment]
@cathywu This is the overall plot. Qijian had a ton of insights as to how to improve the data analysis, but unfortunately his only suggestion as to the spikes is that it might come from errors in NGSIM when the car being tracked is passed from camera to camera
