### ISSUE TITLE
Is IDM plant stable? 

### ISSUE THREAD

**Issue by eugenevinitsky** [cathywu/learning-traffic#52]
It should be plant stable, but mathematica suggests that it isn't.

**Comment by cathywu** [comment]
Gabor's paper "Optimal Control of Connected Vehicle Systems With
Communication Delay and Driver Reaction Time" says they only study non-CCC
models which are plant stable, i.e. they *assume* that their non-CCC models
are plant stable. They study OVM and IDM. So they assume that those models
are plant stable.

**Comment by cathywu** [comment]
Note: But OVM is plant stable, as confirmed by Mathmatica.

**Comment by cathywu** [comment]
Resolving (because we have a plant-stable model to work with) until we need to deal with IDM.
